spring:
  mvc:
    view:
      prefix: /WEB-INF双击查看原图iews/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3307/panda?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.example.demo.Dao